### ISSUE TITLE
new version?

### ISSUE THREAD

**Issue by johnynek** [twitter/summingbird#649]
It would be good to get a version with this fix: #648

**Comment by johnynek** [comment]
actually #647

**Comment by ianoc** [comment]
Yeah, whats the priority of it? My understanding is that without the redundant also things should be ok?

**Comment by johnynek** [comment]
I think any also at all will cause the ConcurrentMemory platform from
working, and any platform using dependantsAfterMerge, such as:
https://github.com/danielhfrank/summingbird-nsq

On Tue, Jan 12, 2016 at 11:29 AM, ianoc <notifications@github.com> wrote:

> Yeah, whats the priority of it? My understanding is that without the
> redundant also things should be ok?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/summingbird/issues/649#issuecomment-171025779>
> .
>



-- 
P. Oscar Boykin, Ph.D. | http://twitter.com/posco | http://pobox.com/~boykin

**Comment by ianoc** [comment]
Yeah, seems like it should be done. Don't think we'll have time in the short term tho, lots on the go. If you had time you could do it? or Sam?

**Comment by johnynek** [comment]
Huh, guess sonatype does not care that I don't work at Twitter anymore.

**Comment by ianoc** [comment]
Don't think so? Don't think its tied up in that way. Let me know if you get blocked with sonatype tho

**Comment by isnotinvain** [comment]
I think your creds should all be fine. If your gpg key is tied to an @twitter.com email address you might have issue? Though probably not really.
